[feat] #42 사전알림 기능 구현
Leets-Official/Leets-BE pull request #45
Opened 2024-12-02 16:16 UTC by jwnnoh

## 1. 무슨 이유로 코드를 변경했나요?
### 동아리 사전 알림 기능을 구현하기 위함입니다.
- 사전 알림을 받기 위한 이메일 등록 기능을 구현하였습니다.
  - 이메일을 저장하기 위해 `RecruitMail` 객체를 생성하였습니다.
- 크론잡을 통해 지정 시간대에 `RecruitMail` 테이블에 존재하는 모든 이메일에게 모집 시작 안내 메일을 발송합니다.
  - 모집 시작 안내 메일에는 **지원하기** 페이지로 이동하는 버튼이 존재합니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
- 특이사항 없습니다.
<br>

## 3. 관련 스크린샷을 첨부해주세요.
### 메일 발송 결과
<img width="1001" alt="스크린샷 2024-12-03 오전 1 08 50" src="https://github.com/user-attachments/assets/e2b92a0f-3b14-47e6-a8b9-e3b3e59a2a6f">

### 메일 등록 결과
<img width="1401" alt="image" src="https://github.com/user-attachments/assets/67af1557-4b9b-4aa9-939c-31da35a2bf64">

<br>

## 4. 완료 사항
- [x] 모집 알림 신청(이메일 등록) 기능 구현
- [x] 모집 알림 메일 템플릿 생성
- [x] 모집 알림 발송 기능 구현 
<br>

## 5. 추가 사항
- `@Valid` 어노테이션을 통해 DTO 값 검증을 진행해줍니다.
- `BindExceptionResponse` 객체를 통해 검증 예외를 처리합니다.

2024-12-03 03:43 UTC, ay-eonii requested changes
컨벤션만 수정해주세요 ~ 

그리고 질문 몇개 남겼습니다!

2024-12-03 03:43 UTC, ay-eonii commented on src/main/java/land/leets/global/error/BindExceptionResponse.java
> +}
ErrorReponse가 있는데 별도로 만들어 사용하는 이유가 있나요?

2024-12-03 03:43 UTC, ay-eonii commented on src/main/java/land/leets/domain/mail/usecase/SendMailCron.java
> +	// @Scheduled(cron = "0 0 00 ?? 3 ?")
ㅋㅋㅋ 아무렇게나 적고 주석하는 게 웃기네요

2024-12-03 03:43 UTC, ay-eonii commented on src/main/java/land/leets/global/advice/ExceptionHandleAdvice.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
해당 예외는 언제 발생하나요 ?

2024-12-03 03:43 UTC, ay-eonii commented on src/main/java/land/leets/domain/mail/usecase/SendRecruitMail.java
> +    private static final String MAIL_TITLE = "[Leets] 5기 모집 시작 안내 메일입니다.";
```suggestion
public class SendRecruitMail {

    private static final String MAIL_TITLE = "[Leets] 5기 모집 시작 안내 메일입니다.";
```

개행 부탁드립니다~

2024-12-03 03:43 UTC, ay-eonii commented on src/main/java/land/leets/domain/mail/controller/dto/RecruitMailRequest.java
> +        @Email @NotBlank String email
```suggestion
        @Email 
        @NotBlank 
        String email
```

2024-12-03 04:46 UTC, jwnnoh commented on src/main/java/land/leets/global/advice/ExceptionHandleAdvice.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
해당 예외는 컨트롤러에서 `@Valid` 어노테이션을 통해 Body의 이메일 필드를 검증했을 때 올바르지 않은 형식일 경우 발생합니다.
`RequestParam`으로 진행할 경우 `BindException`이 발생하지만, 해당 기능의 경우 Body를 통해 값을 전달하기 때문에 `MethodArgumentNotValidException`이 발생합니다!

2024-12-03 04:47 UTC, jwnnoh commented on src/main/java/land/leets/domain/mail/usecase/SendMailCron.java
> +	// @Scheduled(cron = "0 0 00 ?? 3 ?")
ㅎㅎ..5기 일정 확정되면 수정할 에정쿵냐리

2024-12-03 04:51 UTC, jwnnoh commented on src/main/java/land/leets/global/error/BindExceptionResponse.java
> +}
좋은 질문입니다.. 사실 기존 응답 객체를 활용해야 할지에 대해서 많은 고민을 두었는데, 새로운 응답 객체를 만든 이유는 다음과 같습니다.
1. 기존 응답 객체의 생성자는 `상태 코드`, `Message`, `식별 코드` 총 세 가지의 매개변수를 통해서 생성됩니다.
2. `MethodArgumentNotValidException`을 반환할 경우 `식별 코드`와 `Message`만 받아올 수 있습니다.
3. 따라서 `식별 코드`를 검증 타입에 맞추어 일일히 매핑해주어야 하는 번거로움이 크다고 생각하여, 별도의 응답 객체를 만들어서 사용하였습니다.

사실 별도의 생성자를 통해 기존 응답 객체의 마지막 값인 `식별 코드`를 `null`로 반환할까 생각도 하였지만, 불필요한 값이 전송되는 것은 좋지 않을 것 같다는 생각에 현재 안을 선택하였습니다. 😄

2024-12-05 07:54 UTC, jwnnoh commented on src/main/java/land/leets/global/error/BindExceptionResponse.java
> +}
검증 로직 한 곳에서만 사용하려고 응답 객체를 별도로 새로 생성해주는 것은 아연님 말씀대로 불필요한 것 같네..ㅎ,ㅎ

제시해주신 대로 에러 코드를 생성해 준 다음, 포맷 연산자를 통해 검증 오류가 발생한 필드를 List 형식으로 message에 담아주도록 수정하였습니다.☺️

2024-12-05 08:16 UTC, jwnnoh commented on src/main/java/land/leets/global/error/BindExceptionResponse.java
> +}
추가적으로 언급해주신 불필요한 포맷 연산자를 제외하고, 검증 시 결과를 스크린샷에 첨부하였습니다!

2024-12-05 08:27 UTC, merged